"""empty message

Revision ID: 13d4e255c080
Revises: 3c7fb4d22df6
Create Date: 2024-12-06 22:10:52.235196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d4e255c080'
down_revision = '3c7fb4d22df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments_bank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threeDId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'three_d_bank', ['threeDId'], ['id'])

    with op.batch_alter_table('three_d_bank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imageUrl', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['userId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('three_d_bank', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('imageUrl')
        batch_op.drop_column('description')

    with op.batch_alter_table('comments_bank', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('threeDId')

    # ### end Alembic commands ###
